"""Add valorant_tracker column

Revision ID: 08698af6e67c
Revises: c0b66b876229
Create Date: 2024-09-20 13:40:12.394765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08698af6e67c'
down_revision = 'c0b66b876229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valorant_tracker', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('discord_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('tracker_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracker_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('discord_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('clip')
        batch_op.drop_column('valorant_tracker')

    # ### end Alembic commands ###
