"""Remove clip from submission model

Revision ID: 6b45455230c3
Revises: 08698af6e67c
Create Date: 2024-09-20 15:08:58.784459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b45455230c3'
down_revision = '08698af6e67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('clip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('video_link')

    # ### end Alembic commands ###
